#+TITLE: Notes of Org-mode
#+OPTIONS: toc:nil
* Commands
=/C-u TAB(org-global-cycle)/=

Global cycling: Rotate the entire buffer among the states.
OVERVIEW -> CONTENTS -> SHOW ALL

=/C-c C-x b(org-tree-to-indirect-buffer)/=

Show the current subtree in an indirect buffer.

=M-RET(org-meta-return)=

Insert a new heading, item or row.

=M-x org-entities-help=

Check out org entities help.

=M-x customize-face=

Customize face.

=C-c a +prefix=

Org agenda prefix.

=C-c C-l=

Add a link.

=C-c C-d=

Deadline timestamp.

=C-c C-s=

Schedule timestamp.

=C-c .=

Add a timestamp.

=C-c ,=

Set priority of TODO item. S-UP and S-DOWN to change this.

=C-c C-q=

Set tags.

=C-c \ +prefix=

Build a sparse tree using title searched.

=C-c \slash +prefix=

Build a sparse tree.

=C-c a +prefix=

View todo list in a view.

=C-c [=

Add current file to agenda file list.

=C-c ]=

Remove current file from agenda file list.
* Special Text Mark
*bold*
/italic/
_underline_
=code=
~verbatim~
+strike-through+
* Header
=#+OPTIONS: \n:t/=

Start a newline when you press RET.

=#+OPTIONS: toc:nil=

Disable defaultly adding table of contents(TOC) when exporting.
